### LOOK AND FEEL

# Theme: https://github.com/scottmckendry/cyberdream.nvim
include themes/cyberdream.conf

# Transparency
background_opacity 0.9
background_blur 8

# Font: https://github.com/ryanoasis/nerd-fonts
# `brew install --cask font-jetbrains-mono-nerd-font`
font_size 14.0
font_family      family='JetBrainsMono Nerd Font Mono'
bold_font        family='JetBrainsMono Nerd Font Mono' style=Bold
italic_font      auto
bold_italic_font family='JetBrainsMono Nerd Font Mono' style='Bold Italic'

### WINDOW/TAB MANAGEMENT

remember_window_size  yes
# initial_window_width  640
# initial_window_height 400

window_border_width 1pt
tab_bar_edge top

# Overwrite default new window mapping
map cmd+enter launch --cwd=current --location=vsplit

# Move current window
map shift+up move_window up
map shift+down move_window down
map shift+left move_window left
map shift+right move_window right

# Move window focus
map ctrl+up neighboring_window top
map ctrl+down neighboring_window bottom
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right

### MISC
macos_option_as_alt yes

# Enable link clicking
mouse_map left click ungrabbed mouse_handle_click selection link prompt
mouse_map shift+left click grabbed,ungrabbed mouse_handle_click selection link prompt
mouse_map ctrl+shift+left release grabbed,ungrabbed mouse_handle_click link

# Map Cmd to Ctrl for common Neovim shortcuts 
# map cmd+d send_text all \x04
# map cmd+u send_text all \x15
# map cmd+f send_text all \x06
# map cmd+b send_text all \x02
# map cmd+w send_text all \x17
# map cmd+r send_text all \x12
# map cmd+o send_text all \x0f
# map cmd+i send_text all \x09
# map cmd+[ send_text all \x1b
# map cmd+] send_text all \x1d
# map cmd+a send_text all \x01
# map cmd+e send_text all \x05
# map cmd+p send_text all \x10
# map cmd+n send_text all \x0e
# map cmd+l send_text all \x0c
# map cmd+g send_text all \x07
# map cmd+h send_text all \x08
# map cmd+j send_text all \x0a
# map cmd+k send_text all \x0b
# map cmd+z send_text all \x1a
